/**
 * Bot Version Configuration
 * This file contains the current version of the ADA Futures Trading Bot
 */

export const BOT_VERSION = '1.3.5';

export const VERSION_INFO = {
  version: BOT_VERSION,
  buildDate: new Date().toISOString(),
  features: [
    'Sequential Position Management',
    'Hybrid Timing System (2min heavy + 20s quick)',
    'Comprehensive 51-Level System',
    'Dynamic Level Learning',
    'Bidirectional Trading (LONG/SHORT)',
    'Liquidation-Based Hedging',
    'Price Peak Detection',
    'Target Return Exit',
    'Dynamic Balance System',
    'Real-time Price Updates (20s)',
    'Global Configuration System',
    'Multi-Pair Trading Support',
    'Emergency Hedge Leverage',
    'Centralized Environment Management',
    'Fixed Position Type Determination Logic',
    'Fixed Hardcoded Leverage Override Bug',
    'Hedge Exit Price Calculation System',
    'Mathematical Hedge Closure Logic',
    'Leverage-Adjusted Hedge Analysis',
    'Fee-Aware Hedge Closure Logic',
    'Corrected Binance Futures Fee Calculations',
    'Leverage-Adjusted Fee Calculations',
    'VWAP Integration for Market Sentiment Analysis',
    'Liquidity Zone Calculation for Zone-Based Hedging',
    'Buffer Zone Implementation for Strategic Hedge Placement',
    'VWAP Zone Activation Logic for Buffer Zone Signals',
    'Hedge Leverage Multiplier (Primary × 2) for Faster Profit Growth',
    'Single VWAP Signal Confirmation for Hedge Entry',
    'Distributed Hedging Strategy with Secondary API Key for Anti-Detection',
    'Conditional Scalp Activation Based on High-Volume Conditions',
    'Corrected Exit Logic - Primary TP Exits + Hedge System Risk Management',
    'Cross-Pair Primary Position Limiting System (Max 2 Primary Positions)',
    'Single API Key Mode for Simplified Hedge Management',
    'AI-Powered Market Analysis with DeepSeek API Integration',
    'Sentiment Analysis for Market Mood Detection',
    'Advanced Pattern Recognition for Technical Validation',
    'Market Regime Detection for Adaptive Strategy Parameters',
    'AI Risk Assessment and Dynamic Position Sizing',
    'Correlation Analysis for Multi-Asset Context',
    'AI Signal Filtering and Confidence Scoring',
    'Intelligent Signal Enhancement with Machine Learning',
    'Optimized AI Market Analysis (Every 15 minutes)',
    'AI-Powered Entry/Exit Decision Making',
    'Comprehensive AI Fallback Mechanisms',
    'AI Configuration Management System',
    'Advanced AI Testing and Validation Framework',
    'Frequent Trading Strategy with 1% Profit Targets',
    'Position Size-Based Profit Calculation',
    'Optimized Exit Logic for High-Frequency Trading',
    'DeepSeek API Cost Optimization (90-95% reduction)',
    'Intelligent Caching with Volatility-Based Duration',
    'Batch AI Analysis (4 calls reduced to 1)',
    'Circuit Breaker Pattern for API Protection',
    'Optimized Analysis Intervals (15-minute heavy analysis)',
    'Standalone Operation Mode (No UI Dependencies)',
    'CRITICAL: Fixed Signal Generation Logic (Support/Resistance Classification)',
    'Enhanced Entry Validation with Volume Confirmation',
    'RSI Oversold/Overbought Requirements for Entries',
    'VWAP Confirmation for Entry Direction Validation',
    'Pre-Entry Signal Validation System',
    'Fixed Level Classification Issues (Resistance vs Support)',
    'Comprehensive Entry Safety Checks',
    'High-Frequency Trading Strategy (0.6% Profit Targets)',
    'Advanced Technical Indicators (Stochastic RSI, Bollinger Bands, ATR, MFI, MACD, Awesome Oscillator, TRIX, PSAR)',
    'Configurable Max Position Size',
    'Strategy Isolation (Hedge, Opportunity, Scalp Disabled)',
    'Pure High-Frequency Mode',
    'ROI-Based Exit Monitoring System',
    'Real-Time ROI Analysis and Logging',
    'Enhanced Exit Logic with ROI Priority',
    'Complete Strategy Isolation - HF Only Mode',
    'Removed Hedge and Scalp Strategy Dependencies',
    'Pure High-Frequency Trading Architecture',
    'MAJOR: Clean HF-Only Architecture Implementation',
    'Eliminated All Strategy Conflicts and Dependencies',
    'Optimized Memory Usage and Startup Performance',
    'CRITICAL: Fixed Position Size Configuration Issue',
    'Corrected Hardcoded 20% Default Override Bug',
    'Fixed HF_POSITION_SIZE and MAX_POSITION_SIZE Environment Variable Loading',
    'FIXED: Position Type Classification in Hedge Monitoring',
    'Added HF Position Type Support to HedgeMonitor Interface',
    'Fixed Position Type Filtering for HF-Only Mode',
    'Enhanced ROI Monitoring Visibility (Debug to Info Logging)',
    'Improved Hedge Size and Leverage Configuration for HF Positions',
    'CRITICAL: Fixed Missing TP Orders for Existing Positions',
    'Added Automatic TP Setting for Positions Without TP Orders',
    'Fixed ROI Monitoring to Monitor All Open Positions',
    'Enhanced Position Protection Against Liquidation',
    'Added TP Order Detection and Validation System',
    'NEW: HF Entry Price Buffer System (2% Better Execution)',
    'Enhanced HF Position Entry Logic with Price Optimization',
    'Improved Entry Execution for LONG and SHORT Positions',
    'Added Entry Price Buffer Logging and Monitoring',
    'Optimized HF Strategy for Better Profit Margins',
    'MAJOR: S/R Level-Based Entry Pricing System',
    'Replaced Buffer Logic with Intelligent Market Structure Entry',
    'Historical Support/Resistance Level Integration',
    'Dynamic S/R Level Learning for Entry Optimization',
    'Enhanced Entry Price Calculation with Market Structure'
  ],
  strategies: [
    'High-Frequency Strategy (0.6% Profit Targets)',
    'Advanced Technical Analysis (8 Indicators)',
    'Dynamic Position Sizing',
    'Signal Strength Analysis',
    'ATR-Based Risk Management',
    'AI-Enhanced Signal Generation',
    'Intelligent Market Regime Adaptation',
    'AI-Powered Risk Management',
    'Enhanced Entry Validation Strategy',
    'Multi-Criteria Entry Confirmation System'
  ],
  safety: [
    'Mathematical Profit Guarantee',
    'ISOLATED Margin Mode',
    'Automatic Error Recovery',
    'Comprehensive Logging',
    'AI-Powered Risk Assessment',
    'Intelligent Signal Filtering',
    'AI Fallback Mechanisms',
    'Advanced Error Handling with AI Context',
    'CRITICAL: Entry Validation Safety System',
    'Volume Confirmation Requirements',
    'RSI-Based Entry Safety Checks',
    'VWAP-Based Entry Direction Validation',
    'Pre-Entry Signal Validation'
  ]
};

export default BOT_VERSION;
